#!/bin/csh
# runall-jaxrpc
if (! $?STANDALONE_MODE) then
 setenv STANDALONE_MODE true
endif
echo STANDALONE_MODE=$STANDALONE_MODE
stoptc
cd $TS_HOME/src/com/sun/ts/tests/jaxrpc
if ("$STANDALONE_MODE" == "false" ) then
  echo "Running with JWSDP release ... no setup needed"
  echo "cp -f $TS_HOME/lib/tsharness.jar $CATALINA_HOME/common/lib"
  cp -f $TS_HOME/lib/tsharness.jar $CATALINA_HOME/common/lib
else
  echo "Setup for standalone JAXRPC run ..."
  echo "Running with standalone JAXRPC release ... perform setup"
  setup-jaxrpc
endif
setenv clean 1
setenv build 1
setenv undeploy 1
setenv deploy 1
if ($clean == "1") then
    echo "Clean JAXRPC TCK ....."
    test.ksh -p a -c
    cd $TS_HOME/src/com/sun/ts/tests/signaturetest/jaxrpc
    test.ksh -p a -c
    cat clean*log >>$TS_HOME/src/com/sun/ts/tests/jaxrpc/clean*log
    cd $TS_HOME/src/com/sun/ts/tests/jaxrpc
endif
if ($build == "1") then
    echo "Build JAXRPC TCK ....."
    test.ksh -p a -b
    cd $TS_HOME/src/com/sun/ts/tests/signaturetest/jaxrpc
    test.ksh -p a -b
    cat build*log >> $TS_HOME/src/com/sun/ts/tests/jaxrpc/build*log
    cd $TS_HOME/src/com/sun/ts/tests/jaxrpc
endif
if ($undeploy == "1") then
    echo "Undeploy JAXRPC TCK ....."
    test.ksh -p a -u
endif
if ($deploy == "1") then
    echo "Deploy JAXRPC TCK ....."
    test.ksh -p a -d
endif
starttc&
echo "Sleeping 3 minutes ..."
sleep 180
echo "Run JAXRPC TCK against WebServer $WEBSERVER_HOME ....."
cd $TS_HOME/src/com/sun/ts/tests/jaxrpc
test.ksh -p a -r
cd $TS_HOME/src/com/sun/ts/tests/signaturetest/jaxrpc
test.ksh -p a -r
cat - >> $TS_HOME/src/com/sun/ts/tests/jaxrpc/run*log <<EOF
------------------
Signature Test Run
------------------
EOF
cat run*log >> $TS_HOME/src/com/sun/ts/tests/jaxrpc/run*log
cd $TS_HOME/src/com/sun/ts/tests/jaxrpc
