#!/bin/csh
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
#
# The contents of this file are subject to the terms of either the GNU
# General Public License Version 2 only ("GPL") or the Common Development
# and Distribution License("CDDL") (collectively, the "License").  You
# may not use this file except in compliance with the License.  You can
# obtain a copy of the License at
# https://oss.oracle.com/licenses/CDDL+GPL-1.1
# or LICENSE.txt.  See the License for the specific
# language governing permissions and limitations under the License.
#
# When distributing the software, include this License Header Notice in each
# file and include the License file at LICENSE.txt.
#
# GPL Classpath Exception:
# Oracle designates this particular file as subject to the "Classpath"
# exception as provided by Oracle in the GPL Version 2 section of the License
# file that accompanied this code.
#
# Modifications:
# If applicable, add the following below the License Header, with the fields
# enclosed by brackets [] replaced by your own identifying information:
# "Portions Copyright [year] [name of copyright owner]"
#
# Contributor(s):
# If you wish your version of this file to be governed by only the CDDL or
# only the GPL Version 2, indicate your decision by adding "[Contributor]
# elects to include this software in this distribution under the [CDDL or GPL
# Version 2] license."  If you don't indicate a single choice of license, a
# recipient has the option to distribute your version of this file under
# either the CDDL, the GPL Version 2 or to extend the choice of license to
# its licensees as provided above.  However, if you add GPL Version 2 code
# and therefore, elected the GPL Version 2 license, then the option applies
# only if the new code is made subject to such option by the copyright
# holder.
#

# runall-jaxrpc
if (! $?STANDALONE_MODE) then
 setenv STANDALONE_MODE true
endif
echo STANDALONE_MODE=$STANDALONE_MODE
stoptc
cd $TS_HOME/src/com/sun/ts/tests/jaxrpc
if ("$STANDALONE_MODE" == "false" ) then
  echo "Running with JWSDP release ... no setup needed"
  echo "cp -f $TS_HOME/lib/tsharness.jar $CATALINA_HOME/common/lib"
  cp -f $TS_HOME/lib/tsharness.jar $CATALINA_HOME/common/lib
else
  echo "Setup for standalone JAXRPC run ..."
  echo "Running with standalone JAXRPC release ... perform setup"
  setup-jaxrpc
endif
setenv clean 1
setenv build 1
setenv undeploy 1
setenv deploy 1
if ($clean == "1") then
    echo "Clean JAXRPC TCK ....."
    test.ksh -p a -c
    cd $TS_HOME/src/com/sun/ts/tests/signaturetest/jaxrpc
    test.ksh -p a -c
    cat clean*log >>$TS_HOME/src/com/sun/ts/tests/jaxrpc/clean*log
    cd $TS_HOME/src/com/sun/ts/tests/jaxrpc
endif
if ($build == "1") then
    echo "Build JAXRPC TCK ....."
    test.ksh -p a -b
    cd $TS_HOME/src/com/sun/ts/tests/signaturetest/jaxrpc
    test.ksh -p a -b
    cat build*log >> $TS_HOME/src/com/sun/ts/tests/jaxrpc/build*log
    cd $TS_HOME/src/com/sun/ts/tests/jaxrpc
endif
if ($undeploy == "1") then
    echo "Undeploy JAXRPC TCK ....."
    test.ksh -p a -u
endif
if ($deploy == "1") then
    echo "Deploy JAXRPC TCK ....."
    test.ksh -p a -d
endif
starttc&
echo "Sleeping 3 minutes ..."
sleep 180
echo "Run JAXRPC TCK against WebServer $WEBSERVER_HOME ....."
cd $TS_HOME/src/com/sun/ts/tests/jaxrpc
test.ksh -p a -r
cd $TS_HOME/src/com/sun/ts/tests/signaturetest/jaxrpc
test.ksh -p a -r
cat - >> $TS_HOME/src/com/sun/ts/tests/jaxrpc/run*log <<EOF
------------------
Signature Test Run
------------------
EOF
cat run*log >> $TS_HOME/src/com/sun/ts/tests/jaxrpc/run*log
cd $TS_HOME/src/com/sun/ts/tests/jaxrpc
